package sap_api_output_formatter

type Header struct {
	FiscalYear                      string      `json:"FiscalYear"`
	PhysicalInventoryDocument       string      `json:"PhysicalInventoryDocument"`
	InventoryTransactionType        string      `json:"InventoryTransactionType"`
	Plant                           string      `json:"Plant"`
	StorageLocation                 string      `json:"StorageLocation"`
	InventorySpecialStockType       string      `json:"InventorySpecialStockType"`
	DocumentDate                    string      `json:"DocumentDate"`
	PhysInventoryPlannedCountDate   string      `json:"PhysInventoryPlannedCountDate"`
	PhysicalInventoryLastCountDate  string      `json:"PhysicalInventoryLastCountDate"`
	PostingDate                     string      `json:"PostingDate"`
	FiscalPeriod                    string      `json:"FiscalPeriod"`
	PostingIsBlockedForPhysInvtry   bool        `json:"PostingIsBlockedForPhysInvtry"`
	PhysicalInventoryCountStatus    string      `json:"PhysicalInventoryCountStatus"`
	PhysInvtryAdjustmentPostingSts  string      `json:"PhysInvtryAdjustmentPostingSts"`
	PhysInvtryDeletionStatus        string      `json:"PhysInvtryDeletionStatus"`
	PhysInvtryDocHasQtySnapshot     bool        `json:"PhysInvtryDocHasQtySnapshot"`
	PhysicalInventoryGroupType      string      `json:"PhysicalInventoryGroupType"`
	PhysicalInventoryGroup          string      `json:"PhysicalInventoryGroup"`
	PhysicalInventoryNumber         string      `json:"PhysicalInventoryNumber"`
	PhysInventoryReferenceNumber    string      `json:"PhysInventoryReferenceNumber"`
	PhysicalInventoryDocumentDesc   string      `json:"PhysicalInventoryDocumentDesc"`
	PhysicalInventoryType           string      `json:"PhysicalInventoryType"`
	LastChangeDateTime              string      `json:"LastChangeDateTime"`
	ToItem                          string      `json:"to_PhysicalInventoryDocumentItem"`
}

type Item struct {
	FiscalYear                     string      `json:"FiscalYear"`
	PhysicalInventoryDocument      string      `json:"PhysicalInventoryDocument"`
	PhysicalInventoryDocumentItem  string      `json:"PhysicalInventoryDocumentItem"`
	Plant                          string      `json:"Plant"`
	StorageLocation                string      `json:"StorageLocation"`
	Material                       string      `json:"Material"`
	Batch                          string      `json:"Batch"`
	InventorySpecialStockType      string      `json:"InventorySpecialStockType"`
	PhysicalInventoryStockType     string      `json:"PhysicalInventoryStockType"`
	SalesOrder                     string      `json:"SalesOrder"`
	SalesOrderItem                 string      `json:"SalesOrderItem"`
	Supplier                       string      `json:"Supplier"`
	Customer                       string      `json:"Customer"`
	WBSElement                     string      `json:"WBSElement"`
	LastChangeDate                 string      `json:"LastChangeDate"`
	CountedByUser                  string      `json:"CountedByUser"`
	PhysicalInventoryLastCountDate string      `json:"PhysicalInventoryLastCountDate"`
	AdjustmentPostingMadeByUser    string      `json:"AdjustmentPostingMadeByUser"`
	PostingDate                    string      `json:"PostingDate"`
	PhysicalInventoryItemIsCounted bool        `json:"PhysicalInventoryItemIsCounted"`
	PhysInvtryDifferenceIsPosted   bool        `json:"PhysInvtryDifferenceIsPosted"`
	PhysInvtryItemIsRecounted      bool        `json:"PhysInvtryItemIsRecounted"`
	PhysInvtryItemIsDeleted        bool        `json:"PhysInvtryItemIsDeleted"`
	IsHandledInAltvUnitOfMsr       bool        `json:"IsHandledInAltvUnitOfMsr"`
	CycleCountType                 string      `json:"CycleCountType"`
	IsValueOnlyMaterial            bool        `json:"IsValueOnlyMaterial"`
	PhysInventoryReferenceNumber   string      `json:"PhysInventoryReferenceNumber"`
	MaterialDocument               string      `json:"MaterialDocument"`
	MaterialDocumentYear           string      `json:"MaterialDocumentYear"`
	MaterialDocumentItem           string      `json:"MaterialDocumentItem"`
	PhysInvtryRecountDocument      string      `json:"PhysInvtryRecountDocument"`
	PhysicalInventoryItemIsZero    bool        `json:"PhysicalInventoryItemIsZero"`
	ReasonForPhysInvtryDifference  string      `json:"ReasonForPhysInvtryDifference"`
	MaterialBaseUnit               string      `json:"MaterialBaseUnit"`
	BookQtyBfrCountInMatlBaseUnit  string      `json:"BookQtyBfrCountInMatlBaseUnit"`
	Quantity                       string      `json:"Quantity"`
	UnitOfEntry                    string      `json:"UnitOfEntry"`
	QuantityInUnitOfEntry          string      `json:"QuantityInUnitOfEntry"`
	Currency                       string      `json:"Currency"`
	LastChangeDateTime             string      `json:"LastChangeDateTime"`
}

type ToItem struct {
	FiscalYear                     string      `json:"FiscalYear"`
	PhysicalInventoryDocument      string      `json:"PhysicalInventoryDocument"`
	PhysicalInventoryDocumentItem  string      `json:"PhysicalInventoryDocumentItem"`
	Plant                          string      `json:"Plant"`
	StorageLocation                string      `json:"StorageLocation"`
	Material                       string      `json:"Material"`
	Batch                          string      `json:"Batch"`
	InventorySpecialStockType      string      `json:"InventorySpecialStockType"`
	PhysicalInventoryStockType     string      `json:"PhysicalInventoryStockType"`
	SalesOrder                     string      `json:"SalesOrder"`
	SalesOrderItem                 string      `json:"SalesOrderItem"`
	Supplier                       string      `json:"Supplier"`
	Customer                       string      `json:"Customer"`
	WBSElement                     string      `json:"WBSElement"`
	LastChangeDate                 string      `json:"LastChangeDate"`
	CountedByUser                  string      `json:"CountedByUser"`
	PhysicalInventoryLastCountDate string      `json:"PhysicalInventoryLastCountDate"`
	AdjustmentPostingMadeByUser    string      `json:"AdjustmentPostingMadeByUser"`
	PostingDate                    string      `json:"PostingDate"`
	PhysicalInventoryItemIsCounted bool        `json:"PhysicalInventoryItemIsCounted"`
	PhysInvtryDifferenceIsPosted   bool        `json:"PhysInvtryDifferenceIsPosted"`
	PhysInvtryItemIsRecounted      bool        `json:"PhysInvtryItemIsRecounted"`
	PhysInvtryItemIsDeleted        bool        `json:"PhysInvtryItemIsDeleted"`
	IsHandledInAltvUnitOfMsr       bool        `json:"IsHandledInAltvUnitOfMsr"`
	CycleCountType                 string      `json:"CycleCountType"`
	IsValueOnlyMaterial            bool        `json:"IsValueOnlyMaterial"`
	PhysInventoryReferenceNumber   string      `json:"PhysInventoryReferenceNumber"`
	MaterialDocument               string      `json:"MaterialDocument"`
	MaterialDocumentYear           string      `json:"MaterialDocumentYear"`
	MaterialDocumentItem           string      `json:"MaterialDocumentItem"`
	PhysInvtryRecountDocument      string      `json:"PhysInvtryRecountDocument"`
	PhysicalInventoryItemIsZero    bool        `json:"PhysicalInventoryItemIsZero"`
	ReasonForPhysInvtryDifference  string      `json:"ReasonForPhysInvtryDifference"`
	MaterialBaseUnit               string      `json:"MaterialBaseUnit"`
	BookQtyBfrCountInMatlBaseUnit  string      `json:"BookQtyBfrCountInMatlBaseUnit"`
	Quantity                       string      `json:"Quantity"`
	UnitOfEntry                    string      `json:"UnitOfEntry"`
	QuantityInUnitOfEntry          string      `json:"QuantityInUnitOfEntry"`
	Currency                       string      `json:"Currency"`
	LastChangeDateTime             string      `json:"LastChangeDateTime"`
}
