package sap_api_input_reader

type EC_MC struct {
	ConnectionKey string `json:"connection_key"`
	Result        bool   `json:"result"`
	RedisKey      string `json:"redis_key"`
	Filepath      string `json:"filepath"`
	PhysicalInventoryDocument struct {
		PhysicalInventoryDocument string      `json:"document_no"`
		Plant                     string      `json:"deliver_to"`
		OrderQuantity             string      `json:"quantity"`
		PickedQuantity            string      `json:"picked_quantity"`
		NetPriceAmount            string      `json:"price"`
	    Batch                     string      `json:"batch"`
	} `json:"document"`
	ProductionOrder struct {
		DocumentNo           string      `json:"document_no"`
		Status               string      `json:"status"`
		DeliverTo            string      `json:"deliver_to"`
		Quantity             string      `json:"quantity"`
		CompletedQuantity    string      `json:"completed_quantity"`
	    PlannedStartDate     string      `json:"planned_start_date"`
	    PlannedValidatedDate string      `json:"planned_validated_date"`
	    ActualStartDate      string      `json:"actual_start_date"`
	    ActualValidatedDate  string      `json:"actual_validated_date"`
	    Batch                string      `json:"batch"`
		Work              struct {
			WorkNo                   string      `json:"work_no"`
			Quantity                 string      `json:"quantity"`
			CompletedQuantity        string      `json:"completed_quantity"`
			ErroredQuantity          string      `json:"errored_quantity"`
			Component                string      `json:"component"`
			PlannedComponentQuantity string      `json:"planned_component_quantity"`
			PlannedStartDate         string      `json:"planned_start_date"`
			PlannedStartTime         string      `json:"planned_start_time"`
			PlannedValidatedDate     string      `json:"planned_validated_date"`
			PlannedValidatedTime     string      `json:"planned_validated_time"`
			ActualStartDate          string      `json:"actual_start_date"`
			ActualStartTime          string      `json:"actual_start_time"`
			ActualValidatedDate      string      `json:"actual_validated_date"`
			ActualValidatedTime      string      `json:"actual_validated_time"`
		} `json:"work"`
	} `json:"production_order"`
	APISchema                         string `json:"api_schema"`
	Accepter                        []string `json:"accepter"`
	MaterialCode                      string `json:"material_code"`
	Supplier                          string `json:"plant/supplier"`
	Stock                             string `json:"stock"`
	SalesOrderType                    string `json:"document_type"`
	PhysicalInventoryDocumentNo       string `json:"document_no"`
	ScheduleLineDeliveryDate          string `json:"planned_date"`
	ValidatedDate                     string `json:"validated_date"`
    Deleted                           bool   `json:"deleted"`
}

type SDC struct {
	ConnectionKey             string `json:"connection_key"`
	Result                    bool   `json:"result"`
	RedisKey                  string `json:"redis_key"`
	Filepath                  string `json:"filepath"`
	PhysicalInventoryDocument struct {
		FiscalYear                     string      `json:"FiscalYear"`
		PhysicalInventoryDocument      string      `json:"PhysicalInventoryDocument"`
		InventoryTransactionType       string      `json:"InventoryTransactionType"`
		Plant                          string      `json:"Plant"`
		StorageLocation                string      `json:"StorageLocation"`
		InventorySpecialStockType      string      `json:"InventorySpecialStockType"`
		DocumentDate                   string      `json:"DocumentDate"`
		PhysInventoryPlannedCountDate  string      `json:"PhysInventoryPlannedCountDate"`
		PhysicalInventoryLastCountDate string      `json:"PhysicalInventoryLastCountDate"`
		PostingDate                    string      `json:"PostingDate"`
		FiscalPeriod                   string      `json:"FiscalPeriod"`
		PostingIsBlockedForPhysInvtry  bool        `json:"PostingIsBlockedForPhysInvtry"`
		PhysicalInventoryCountStatus   string      `json:"PhysicalInventoryCountStatus"`
		PhysInvtryAdjustmentPostingSts string      `json:"PhysInvtryAdjustmentPostingSts"`
		PhysInvtryDeletionStatus       string      `json:"PhysInvtryDeletionStatus"`
		PhysInvtryDocHasQtySnapshot    bool        `json:"PhysInvtryDocHasQtySnapshot"`
		PhysicalInventoryGroupType     string      `json:"PhysicalInventoryGroupType"`
		PhysicalInventoryGroup         string      `json:"PhysicalInventoryGroup"`
		PhysicalInventoryNumber        string      `json:"PhysicalInventoryNumber"`
		PhysInventoryReferenceNumber   string      `json:"PhysInventoryReferenceNumber"`
		PhysicalInventoryDocumentDesc  string      `json:"PhysicalInventoryDocumentDesc"`
		PhysicalInventoryType          string      `json:"PhysicalInventoryType"`
		LastChangeDateTime             string      `json:"LastChangeDateTime"`
		PhysicalInventoryDocumentItem  struct {
			PhysicalInventoryDocumentItem  string      `json:"PhysicalInventoryDocumentItem"`
			Plant                          string      `json:"Plant"`
			StorageLocation                string      `json:"StorageLocation"`
			InventorySpecialStockType      string      `json:"InventorySpecialStockType"`
			Material                       string      `json:"Material"`
			Batch                          string      `json:"Batch"`
			PhysicalInventoryStockType     string      `json:"PhysicalInventoryStockType"`
			SalesOrder                     string      `json:"SalesOrder"`
			SalesOrderItem                 string      `json:"SalesOrderItem"`
			Supplier                       string      `json:"Supplier"`
			Customer                       string      `json:"Customer"`
			WBSElement                     string      `json:"WBSElement"`
			LastChangeDate                 string      `json:"LastChangeDate"`
			CountedByUser                  string      `json:"CountedByUser"`
			PhysicalInventoryLastCountDate string      `json:"PhysicalInventoryLastCountDate"`
			AdjustmentPostingMadeByUser    string      `json:"AdjustmentPostingMadeByUser"`
			PostingDate                    string      `json:"PostingDate"`
			PhysicalInventoryItemIsCounted bool        `json:"PhysicalInventoryItemIsCounted"`
			PhysInvtryDifferenceIsPosted   bool        `json:"PhysInvtryDifferenceIsPosted"`
			PhysInvtryItemIsRecounted      bool        `json:"PhysInvtryItemIsRecounted"`
			PhysInvtryItemIsDeleted        bool        `json:"PhysInvtryItemIsDeleted"`
			IsHandledInAltvUnitOfMsr       bool        `json:"IsHandledInAltvUnitOfMsr"`
			CycleCountType                 string      `json:"CycleCountType"`
			IsValueOnlyMaterial            bool        `json:"IsValueOnlyMaterial"`
			PhysInventoryReferenceNumber   string      `json:"PhysInventoryReferenceNumber"`
			MaterialDocument               string      `json:"MaterialDocument"`
			MaterialDocumentYear           string      `json:"MaterialDocumentYear"`
			MaterialDocumentItem           string      `json:"MaterialDocumentItem"`
			PhysInvtryRecountDocument      string      `json:"PhysInvtryRecountDocument"`
			PhysicalInventoryItemIsZero    bool        `json:"PhysicalInventoryItemIsZero"`
			ReasonForPhysInvtryDifference  string      `json:"ReasonForPhysInvtryDifference"`
			MaterialBaseUnit               string      `json:"MaterialBaseUnit"`
			BookQtyBfrCountInMatlBaseUnit  string      `json:"BookQtyBfrCountInMatlBaseUnit"`
			Quantity                       string      `json:"Quantity"`
			UnitOfEntry                    string      `json:"UnitOfEntry"`
			QuantityInUnitOfEntry          string      `json:"QuantityInUnitOfEntry"`
			Currency                       string      `json:"Currency"`
			LastChangeDateTime             string      `json:"LastChangeDateTime"`
		} `json:"PhysicalInventoryDocumentItem"`
	} `json:"PhysicalInventoryDocument"`
	APISchema                   string   `json:"api_schema"`
	Accepter                    []string `json:"accepter"`
	PhysicalInventoryDocumentNo string   `json:"physical_inventory_document"`
	Deleted                     bool     `json:"deleted"`
}
